# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BDS_4E1h5sBgzhMkmeNrhZxO1UtBz_To
"""

def get_media_database():
    return {
        "Knudson": {"use": "Orchids, ferns", "salts_gL": 1.0, "sucrose_gL": 30, "agar_gL": 6},
        "LS": {"use": "Organogenesis, callus, cell culture", "salts_gL": 4.3, "sucrose_gL": 30, "agar_gL": 8},
        "NN": {"use": "Anther culture, haploid production", "salts_gL": 3.5, "sucrose_gL": 100, "agar_gL": 7},
        "White": {"use": "Shoot and root culture", "salts_gL": 1.5, "sucrose_gL": 30, "agar_gL": 7},
        "DKW": {"use": "Woody plants like walnut", "salts_gL": 4.5, "sucrose_gL": 30, "agar_gL": 8},
        "QL": {"use": "Temperate woody species", "salts_gL": 2.8, "sucrose_gL": 30, "agar_gL": 7},
        "SH": {"use": "Cell suspension and callus induction", "salts_gL": 5.0, "sucrose_gL": 30, "agar_gL": 7},
        "Knop": {"use": "Seedlings and simple cultures", "salts_gL": 1.0, "sucrose_gL": 20, "agar_gL": 6},

        "MS": {"use": "General micropropagation", "salts_gL": 4.3, "sucrose_gL": 30, "agar_gL": 8},
        "WPM": {"use": "Woody plant micropropagation", "salts_gL": 2.5, "sucrose_gL": 20, "agar_gL": 7},
        "B5": {"use": "Callus and cell suspension cultures", "salts_gL": 3.2, "sucrose_gL": 30, "agar_gL": 7},
        "N6": {"use": "Cereal and anther culture", "salts_gL": 4.0, "sucrose_gL": 30, "agar_gL": 7}
    }

def print_header():
    print("\n=== Plant Tissue Culture Assistant ===")

def list_media(db):
    print("\nAvailable media:")
    for name, info in db.items():
        print(f" - {name}: {info['use']}")

def view_media_info(db):
    name = input("Enter media name: ").strip()
    name = name[0].upper() + name[1:].lower()
    if name not in db:
        print("Media not found.")
        list_media(db)
        return
    info = db[name]
    print(f"\n{name} medium:")
    print(f" Use: {info['use']}")
    print(f" Salts (g/L): {info['salts_gL']}")
    print(f" Sucrose (g/L): {info['sucrose_gL']}")
    print(f" Agar (g/L): {info['agar_gL']}")

def media_suggestor(db):
    plant_type = input("Plant type: ").strip().lower()
    if explant == "anther":
        suggestion = "NN"
    elif plant_type == "orchid":
        suggestion = "Knudson"
    elif plant_type == "woody":
        suggestion = "DKW"
    elif plant_type == "temperate":
        suggestion = "QL"
    elif explant in ["leaf", "root"]:
        suggestion = "LS"
    elif explant == "seedling":
        suggestion = "Knop"
    else:
        suggestion = "MS"

    print(f"\nSuggested medium: {suggestion} — {db[suggestion]['use']}")

def prepare_media_calculator(db):
    list_media(db)
    choice = input("Choose a medium: ").strip().upper()
    if choice not in db:
        print("Invalid medium.")
        return

    try:
        vol_ml = float(input("Enter final volume (mL): ").strip())
    except:
        print("Invalid value.")
        return

    L = vol_ml / 1000
    info = db[choice]
    salts = info["salts_gL"] * L
    sucrose = info["sucrose_gL"] * L
    agar = info["agar_gL"] * L

    print(f"\nRecipe for {vol_ml} mL of {choice}:")
    print(f" Salts: {salts:.2f} g")
    print(f" Sucrose: {sucrose:.2f} g")
    print(f" Agar: {agar:.2f} g")
    print(" Adjust pH to ~5.7 and autoclave.")

def main():
    db = get_media_database()
    while True:
        print_header()
        print("1. List media")
        print("2. View media info")
        print("3. Media suggestor")
        print("4. Media preparation calculator")
        print("5. Exit")
        ch = input("Choose (1-5): ").strip()

        if ch == "1":
            list_media(db)
        elif ch == "2":
            view_media_info(db)
        elif ch == "3":
            media_suggestor(db)
        elif ch == "4":
            prepare_media_calculator(db)
        elif ch == "5":
            print("Goodbye.")
            break
        else:
            print("Invalid choice.")

main()